add linux questions
nnstu-appmath/kb pull request #18
Opened 2022-11-07 16:33 UTC by van-yak

2022-11-12 10:59 UTC, arybin93 requested changes
Как и договорились, оформить в формате markdown

2022-11-14 14:01 UTC, RuslanShamshetdinov commented on Linux/linux_questions.md
> +
Наверное, стоит расписать уровни более подробно, потому что по написанному я даже не могу понять о чем идет речь и чем они отличаются

2022-11-14 14:01 UTC, RuslanShamshetdinov commented on Linux/linux_questions.md
> +2: Basic multi user mode without NFS
Стоит расписать какие то аббревиатуры, например, что такое NFS?

2022-11-14 14:01 UTC, RuslanShamshetdinov commented on Linux/linux_questions.md
> +Далее ввести пороль
"Пароль"

2022-11-14 14:01 UTC, RuslanShamshetdinov commented on Linux/linux_questions.md
> +Второй способ - запустить редактор разделов жесткого диска Gparted.
Как его запустить, где он находится, что из себя представляет?

2022-11-14 14:01 UTC, RuslanShamshetdinov commented on Linux/linux_questions.md
> +10.Вопрос
Если 10 вопроса нет, то нужно удалить его объявление

2022-11-18 09:47 UTC, MaxBushuev approved these changes
Вопросы неплохие, пояснения интересные и подробные.
Лично я бы еще убрал файл .docx, но в целом все хорошо

2022-11-18 09:51 UTC, RuslanShamshetdinov approved these changes
С моей стороны вопросов больше нет. Замечания были исправлены, спасибо за Gparted, было полезно узнать.

2022-11-18 20:17 UTC, TimofeyPakholkov approved these changes
Хороший FAQ-список для начинающих пользователей.
Пояснения легко читаются и исчерпывающе отвечают на поставленные вопросы.

2022-11-21 16:18 UTC, arybin93 approved these changes
Круто, спасибо!

2022-12-08 16:18 UTC, merged