Apache Thrift
nnstu-appmath/kb pull request #24
Opened 2022-12-16 11:46 UTC by braindeadboooooy

2022-12-16 12:10 UTC, qwertyqwe55 approved these changes
Все отлично! Интересный материал. 
Я бы хотел предложить некоторые изменения:
1. Стоит добавить определение понятий сериализации и десериализации(это в конце твоей статьи), возможно кто-то не знаком
2. По мелочи еще, после генерации кода на Python и Java, ты предлагаешь создать клиент-сервер на Java и Python на английском языке почему-то. Возможно, ты так и задумывал.
3. Возможно еще стоит добавить скриншоты выполнения, но можно обойтись и без этого, так как, в принципе понятно, что выведет программа

2022-12-21 21:26 UTC, braindeadboooooy commented
> 
Спасибо, за содержательные комментарии. Исправил.

2022-12-26 09:38 UTC, arybin93 requested changes
Спасибо за работу. Отписал некоторые комментарии, что можно улучшить.

2022-12-26 09:38 UTC, arybin93 commented on Apache Thrift/apache_thrift.md
> +**Apache Thrift** — это фреймворк для реализации RPC в сервисах с многоязычной поддержкой. **RPC (удаленный вызов процедур)** подобен вызову функции, только он присутствует удаленно на другом сервере
Думаю, хорошо здесь добавить ссылку к материалам [лекции](https://github.com/nnstu-appmath/distributed_systems_course/blob/master/2_Communication/materials.md#remote-procedure-call-rpc)

Там разбирается RPC.

2022-12-26 09:38 UTC, arybin93 commented on Apache Thrift/apache_thrift.md
> +> import org.apache.thrift.TException;
Для удобства использования кода, лучше убрать символы `>` на каждой строке

2022-12-26 09:38 UTC, arybin93 commented on Apache Thrift/apache_thrift.md
> +### Python Multiplication Client[](https://thrift-tutorial.readthedocs.io/en/latest/usage-example.html#python-multiplication-client "Permalink to this headline")
Ссылка не проставилась

2023-01-12 17:16 UTC, braindeadboooooy commented on Apache Thrift/apache_thrift.md
> +### Python Multiplication Client[](https://thrift-tutorial.readthedocs.io/en/latest/usage-example.html#python-multiplication-client "Permalink to this headline")
Спасибо, исправил.

2023-01-14 16:33 UTC, arybin93 approved these changes
Ок, принято, можно мёржить 
@braindeadboooooy и проставить баллы в таблицу

2023-01-15 08:04 UTC, merged