http protocol tutorial
nnstu-appmath/kb pull request #31
Opened 2023-01-15 09:02 UTC by prostoarinaa

2023-01-15 14:44 UTC, arybin93 requested changes
Ок. Здесь с оформлением makdown всё лучше)
Добавил два комментария.
А так после исправления, может ещё Дмитрий посмотреть, если всё ок, можно мёржить и проставлять баллы в табличке.

2023-01-15 14:44 UTC, arybin93 commented on HTTP протокол/HTTP протокол.md
> +
Тоже хорошо бы добавить используемые материалы

2023-01-15 14:44 UTC, arybin93 commented on HTTP протокол/HTTP протокол.md
> +HyperText Transfer Protocol — «протокол передачи гипертекста» — протокол прикладного уровня передачи данных (изначально — в виде гипертекстовых документов в формате HTML, в настоящий момент используе
Вот здесь у нас тоже [REST](https://github.com/nnstu-appmath/kb/blob/master/REST/rest_documentation.md) описывается немного HTTP, может проставить ссылку оттуда на этот материал?
Что-то повторяется, но здесь подробнее описано

2023-01-15 19:37 UTC, Dm1tr1yS commented
Очень интересный материал. Хоть тема для меня новая(до этого остерегался всего, что касается сетей), но на удивление понятная. В целом, ничего нового к предыдущим комментариям добавить не могу. Одобряю

2023-01-15 19:38 UTC, Dm1tr1yS approved these changes

2023-01-16 17:32 UTC, arybin93 requested changes
Ещё ссылку из материалов по REST сюда бы добавить

2023-01-16 17:32 UTC, arybin93 commented on HTTP протокол/HTTP протокол.md
> +HyperText Transfer Protocol — «протокол передачи гипертекста» — протокол прикладного уровня передачи данных (изначально — в виде гипертекстовых документов в формате HTML, в настоящий момент используе
Не добавлена ссылка на этой материал в материале по REST

2023-01-16 17:39 UTC, prostoarinaa commented
Добавила

2023-01-16 17:44 UTC, arybin93 approved these changes

2023-01-16 18:02 UTC, merged