Add files via upload
nnstu-appmath/kb pull request #33
Opened 2023-01-15 10:07 UTC by prostoarinaa

2023-01-15 14:36 UTC, arybin93 requested changes
В целом, всё хорошо. Спасибо за труд) 
Оставил некоторые комментарии, было бы хорошо их учесть

2023-01-15 14:36 UTC, arybin93 commented on XML туториал/XML eXtensible Markup Language.md
> +﻿\*\*XML eXtensible Markup Language - расширяемый язык разметки\*\*
Не работает выделение жирным. Может просто использовать заголовки?
`# XML eXtensible Markup Language - расширяемый язык разметки` -> 
# XML eXtensible Markup Language - расширяемый язык разметки 
или убрать `\` перед `*`. Без них должно сработать: **test**

Пройтись так по всему тексту, поправить

2023-01-15 14:36 UTC, arybin93 commented on XML туториал/XML eXtensible Markup Language.md
> +\==========================================================
Для разделения в тексте, можно использовать последовательность `---`

---

2023-01-15 14:36 UTC, arybin93 commented on XML туториал/XML eXtensible Markup Language.md
> +- XML — используется в SOAP *(всегда)* и REST-запросах *(реже)*;
Может добавить ссылку на какой-нибудь материал по SOAP? 
И REST? 
SOAP у нас вроде не описан, можно хотя бы на вики для начала или на какую-нибудь хорошую статью)
А по REST у нас материал есть, можно на неё добавить: https://github.com/nnstu-appmath/kb/blob/master/REST/rest_documentation.md

2023-01-15 14:36 UTC, arybin93 commented on XML туториал/XML eXtensible Markup Language.md
> +Но, несмотря на разницу моделей, у всех заказчиков будет одна XSD-схема (которая описывает запрос и ответ):
А что такое XSD схема?

2023-01-15 14:36 UTC, arybin93 commented on XML туториал/XML eXtensible Markup Language.md
> +XML пролог
Здесь наверное лучше заголовок добавить?

2023-01-15 14:36 UTC, arybin93 commented on XML туториал/XML eXtensible Markup Language.md
> +
Хорошо бы добавить список использованных материалов и ссылки на них

2023-01-15 14:36 UTC, arybin93 commented on XML туториал/XML eXtensible Markup Language.md
> +## \*\*В чем преимущества использования XML?\*\*
Может добавить ещё недостатки XML?

2023-01-15 19:45 UTC, Dm1tr1yS approved these changes
До этого использовал только формат JSON. Было интересно почитать и про XML. Материал достаточно интересный, хорошо структуирован. Одобряю

2023-01-16 17:45 UTC, arybin93 approved these changes

2023-01-16 18:02 UTC, merged