final version of Git introduction
nnstu-appmath/kb pull request #38
Opened 2023-03-03 22:05 UTC by 1Serhio

2023-03-04 10:42 UTC, gamehunt commented on Git/Git_introduction.md
> +
Вот это и прочие ссылки лучше вставить в конце, как доп. материал, а в разделах писать выдержку из содержания

2023-03-04 10:49 UTC, gamehunt commented on Git/Git_introduction.md
> +Открываем шпаргалку и скачиваем Git на нужную систему, переходя по первым ссылкам. [Руководство к установке](https://git-scm.com/book/ru/v2/Введение-Установка-Git).
#### Ubuntu
```bash
sudo apt-get install git
```
#### Fedora / CentOS
```bash
sudo dnf install git-all
```
#### ArchLinux
```bash
sudo pacman -S git
```

И.т.д для всего материала по ссылке

2023-03-04 10:50 UTC, gamehunt commented on Git/Git_introduction.md
> +Выполняем все пункты [руководства](https://git-scm.com/book/ru/v2/Введение-Первоначальная-настройка-Git), можно пропустить _выбор редактора_ и _настройку ветки по умолчанию_.
Тут можно ограничиться разделом про пользователя + я бы добавил информацию про добавление SSH-ключа

2023-03-04 10:51 UTC, gamehunt commented on Git/Git_introduction.md
> +Клонирование репозитория осуществляется командой `git clone`. Есть несколько способ клонировать репозиторий, но мы воспользуемся SSH-ключом. Посмотрите [видео](https://www.youtube.com/watch?v=4evR80g
Видео про SSH ключ оставляем как дополнительный материал, всю суть надо написать текстом в разделе начальной настройки

2023-03-04 10:52 UTC, gamehunt commented on Git/Git_introduction.md
> +Находим в руководстве команду для нашей системы, с её помощью переходим к каталогу, который хотим сделать репозиторием, и инициализируем его через `git init` [если перейти к каталогу не получается, п
Сюда бы еще информацию про git remote

2023-03-04 10:52 UTC, gamehunt commented on Git/Git_introduction.md
> +Находим в руководстве команду для нашей системы, с её помощью переходим к каталогу, который хотим сделать репозиторием, и инициализируем его через `git init` [если перейти к каталогу не получается, п
https://git-scm.com/docs/git-remote

2023-03-04 10:54 UTC, gamehunt commented on Git/Git_introduction.md
> +Каждый раз, когда вы делаете коммит, вы сохраняете снимок состояния вашего проекта, который позже вы можете восстановить или с которым можно сравнить текущее состояние.
После этого было бы неплохо еще раз повторить про git push, чтобы сохранить логику add -> commit -> push

+ Не хватает информации про git pull / git fetch

2023-03-04 10:55 UTC, gamehunt commented on Git/Git_introduction.md
> +Каждый раз, когда вы делаете коммит, вы сохраняете снимок состояния вашего проекта, который позже вы можете восстановить или с которым можно сравнить текущее состояние.
Также было бы неплохо упомянуть концепцию веток и про git reset

2023-03-04 10:57 UTC, gamehunt commented on Git/Git_introduction.md
> +Каждый раз, когда вы делаете коммит, вы сохраняете снимок состояния вашего проекта, который позже вы можете восстановить или с которым можно сравнить текущее состояние.
https://git-scm.com/book/ru/v2/%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B-Git-%D0%A0%D0%B0%D1%81%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5-%D1%82%D0%B0%D0%B9%D0%BD-reset
https://git-scm.com/docs/git-reset
https://git-scm.com/docs/git-branch
https://git-scm.com/docs/git-checkout

2023-03-04 11:00 UTC, gamehunt submitted a review, later dismissed
.

2023-03-05 07:09 UTC, 1Serhio commented on Git/Git_introduction.md
> +
Дело в том, что действия конкретного подпункта опираются на конкретное руководство. Зачем все ссылки пихать в конец? Чтобы потом читающему было непонятно, за что отвечает конкретная ссылка? 

Вот я захожу в подпункт, у меня есть ссылка на руководство; если у меня возникает проблема, я понимаю, что поможет в её решении конкретно вот это руководство.

2023-03-05 07:11 UTC, 1Serhio commented on Git/Git_introduction.md
> +Открываем шпаргалку и скачиваем Git на нужную систему, переходя по первым ссылкам. [Руководство к установке](https://git-scm.com/book/ru/v2/Введение-Установка-Git).
Ты предлагаешь мне написать команду для скачивания для всех дистрибутивов Linux? Не вижу в этом смысла.

2023-03-05 07:14 UTC, 1Serhio commented on Git/Git_introduction.md
> +Выполняем все пункты [руководства](https://git-scm.com/book/ru/v2/Введение-Первоначальная-настройка-Git), можно пропустить _выбор редактора_ и _настройку ветки по умолчанию_.
Насчёт ограничения разделом про пользователя — соглашусь.

Добавление SSH-ключа перенесу сюда.

2023-03-05 07:14 UTC, 1Serhio commented on Git/Git_introduction.md
> +Находим в руководстве команду для нашей системы, с её помощью переходим к каталогу, который хотим сделать репозиторием, и инициализируем его через `git init` [если перейти к каталогу не получается, п
Посмотрю.

2023-03-05 07:16 UTC, 1Serhio commented on Git/Git_introduction.md
> +Клонирование репозитория осуществляется командой `git clone`. Есть несколько способ клонировать репозиторий, но мы воспользуемся SSH-ключом. Посмотрите [видео](https://www.youtube.com/watch?v=4evR80g
Почему оставляем как дополнительный материал? Разве были какие-то требования касательно этого? Если есть видео, в котором все действия выполнены, не вижу особого смысла просто перепечатывать их в виде текста.

Единственное, что видео может быть в будущем не доступно.

2023-03-05 07:56 UTC, gamehunt commented on Git/Git_introduction.md
> +
Лазать по ссылкам - не удобно. Удобно когда есть конспект, и есть сноска гиперссылкой на последующий материал

2023-03-05 07:57 UTC, gamehunt commented on Git/Git_introduction.md
> +Открываем шпаргалку и скачиваем Git на нужную систему, переходя по первым ссылкам. [Руководство к установке](https://git-scm.com/book/ru/v2/Введение-Установка-Git).
Делаешь _конспект_ того, что у тебя в ссылке. Можешь оставить только для apt-get, если оно тебя смущает.

2023-03-05 07:58 UTC, gamehunt commented on Git/Git_introduction.md
> +Клонирование репозитория осуществляется командой `git clone`. Есть несколько способ клонировать репозиторий, но мы воспользуемся SSH-ключом. Посмотрите [видео](https://www.youtube.com/watch?v=4evR80g
Потому что лазать по внешним ресурсам неудобно. Удобно когда все понятно описано в одном месте. Когда ссылаются на видео это неудобно вдвойне (имхо)

2023-03-05 08:04 UTC, 1Serhio commented on Git/Git_introduction.md
> +
У меня и есть гиперссылка на дополнительный материал конкретно по тому, что я расписываю в том или ином разделе.

Что неудобного в том, чтобы перед чтением раздела увидеть, что автор оставил ссылки на дополнительные материалы конкретно для этого раздела?

2023-03-05 08:08 UTC, 1Serhio commented on Git/Git_introduction.md
> +Открываем шпаргалку и скачиваем Git на нужную систему, переходя по первым ссылкам. [Руководство к установке](https://git-scm.com/book/ru/v2/Введение-Установка-Git).
Ну, установкой Git'a пусть занимается пользователь с использованием ссылок, которые я оставил, у меня тутор не по этому.

2023-03-05 08:12 UTC, 1Serhio commented on Git/Git_introduction.md
> +Клонирование репозитория осуществляется командой `git clone`. Есть несколько способ клонировать репозиторий, но мы воспользуемся SSH-ключом. Посмотрите [видео](https://www.youtube.com/watch?v=4evR80g
Опять же, не понимаю, что неудобного в том, чтобы просто кликнуть по гиперссылке? Если я буду описывать всё, то
1. это займёт много места;
2. это будет не конспект, а учебник.

2023-03-05 08:13 UTC, gamehunt commented on Git/Git_introduction.md
> +
Про перенос в доп раздел тут конкретно про две эти ссылки, ибо из них состоит весь раздел. Оно не несет никакой смысловой нагрузки с точки зрения структуры, и это можно безопасно переместить в конец. 

Можешь оставить ссылки в начале разделов, дело твоё, но подавать через них весь материал, как в некоторых местах, это неудобно, ибо потом придется бегать между вкладками и тратить время и трафик.

2023-03-05 08:17 UTC, gamehunt commented on Git/Git_introduction.md
> +Открываем шпаргалку и скачиваем Git на нужную систему, переходя по первым ссылкам. [Руководство к установке](https://git-scm.com/book/ru/v2/Введение-Установка-Git).
Ну тут спорный момент, но ладно, можешь оставить так.

2023-03-05 08:20 UTC, gamehunt commented on Git/Git_introduction.md
> +Клонирование репозитория осуществляется командой `git clone`. Есть несколько способ клонировать репозиторий, но мы воспользуемся SSH-ключом. Посмотрите [видео](https://www.youtube.com/watch?v=4evR80g
Даже если рассуждать так, как минимум к видео нужно точно добавить текстовый тутор, ибо это банально удобнее и быстрее.

2023-03-05 08:35 UTC, 1Serhio commented on Git/Git_introduction.md
> +
Размещение первой ссылки осуществляется перед разделом, так как её __рекомендуется открыть перед началом прохождения тутора__. Мне запихнуть её в конец и там указать, что было бы здорово перейти по вот этой ссылке и пройти тутор по GitHub, а потом приступать к изучению статьи, так? Это же бессмыслица.

Потом, 
> не несёт смысловой нагрузки

Я строкой ниже прошу перейти по шпаргалке и скачать Git, или мне тоже ссылку на скачивание отправить в конец?

>тратить время и трафик

Этот тутор, да, придётся потратить время, примерно 5 секунд на все ссылки, но ссылки ставятся не просто так, они помогают в обучение, причём времени, потраченного на изучение материала по ссылкам, уйдёт меньше (если уровень *понимание* зафиксировать), так что оно потрачено не зря. А трафик, я же не коммерческий сайт с рекламой пишу и вообще не сайт, где мне нужно удерживать пользователя.

2023-03-05 08:36 UTC, 1Serhio commented on Git/Git_introduction.md
> +Клонирование репозитория осуществляется командой `git clone`. Есть несколько способ клонировать репозиторий, но мы воспользуемся SSH-ключом. Посмотрите [видео](https://www.youtube.com/watch?v=4evR80g
Текстовый тутор добавлю.

2023-03-05 08:42 UTC, 1Serhio commented on Git/Git_introduction.md
> +
>дело твоё, но подавать через них весь материал, как в некоторых местах, это неудобно

Ну, кроме ссылок, тут достаточно много текста

Опять же, я был бы рад не оставлять вообще никаких ссылок, но я не создатель Git, который можем про него всё рассказать, я начал им пользоваться буквально на днях. Свою задачу я видел, как "описать путь, пройдя который, можно сделать то, то и то [например, сделать первый commit]", и иметь базовые представления о том, что ты делаешь, а не просто скинуть перечень команд без какого-либо описания.

2023-03-05 08:53 UTC, gamehunt commented on Git/Git_introduction.md
> +
Хорошо. Это в принципе был общий комментарий, который можно было бы вывести на сообщение к ревью, потому продолжать эту конву смысла нет, все конкретные места уже ниже отмечены.

Касательно первых ссылок, все же что-то мне не нравится. Мб лучше не делать из них отдельный раздел, а просто указать, что перед дальнейшим чтением лучше с этим ознакомиться, посмотри там что-нибудь, может что-нибудь придумаешь. Если не придумаешь, то можно так и оставить, потом поправить всегда можно.

2023-03-05 10:23 UTC, 1Serhio commented on Git/Git_introduction.md
> +Находим в руководстве команду для нашей системы, с её помощью переходим к каталогу, который хотим сделать репозиторием, и инициализируем его через `git init` [если перейти к каталогу не получается, п
Что именно ты хочешь, что бы я рассказал об этой команде?
Я планирую добавить информацию из [этого](https://git-scm.com/book/ru/v2/Основы-Git-Работа-с-удалёнными-репозиториями) раздела в конце, там фигурирует это команда.

2023-03-05 10:25 UTC, 1Serhio commented on Git/Git_introduction.md
> +Находим в руководстве команду для нашей системы, с её помощью переходим к каталогу, который хотим сделать репозиторием, и инициализируем его через `git init` [если перейти к каталогу не получается, п
Важно, что бы желаемое тобой описание функций команды не выходило за категорию "основы". Для определения того, что относится к ней, а что нет, я использую раздел 2 книги по Git.

2023-03-05 10:37 UTC, 1Serhio commented on Git/Git_introduction.md
> +Каждый раз, когда вы делаете коммит, вы сохраняете снимок состояния вашего проекта, который позже вы можете восстановить или с которым можно сравнить текущее состояние.
Насчёт git push/pull/fetch — ок.
Концепция веток немного описана в начале (раздел теории), не уверен, что в __введении по Git__ следует развивать эту тему (это уже раздел 3 книги по Git, к тому же, если уж и описывать, то подробно, а это много времени и места), Аналогично `git reset`, не встречал эту команду в основах по Git.

2023-03-05 11:03 UTC, gamehunt commented on Git/Git_introduction.md
> +Находим в руководстве команду для нашей системы, с её помощью переходим к каталогу, который хотим сделать репозиторием, и инициализируем его через `git init` [если перейти к каталогу не получается, п
git remote -v
git remote add
git remote remove

Это управление удаленной репой, без этого нельзя с нуля репу создать, по любому нужно будет указывать origin, эти три расписать достаточно будет. На той ссылке, что ты кинул, в принципе, все что надо есть вроде.

2023-03-05 11:04 UTC, gamehunt commented on Git/Git_introduction.md
> +Каждый раз, когда вы делаете коммит, вы сохраняете снимок состояния вашего проекта, который позже вы можете восстановить или с которым можно сравнить текущее состояние.
git reset это откат до определенного коммита/состояния репы, было бы неплохо это тут заиметь, но если не хочешь, то можешь не добавлять, не критично

2023-03-09 07:18 UTC, arybin93 requested changes
Спасибо за подготовку материала, выглядит хорошо.
Добавил комментарии, по которым можно ещё пробежаться, не совсем полностью описан наш путь на практике. Я в одном из комментариев описал, как можно сделать, про разделение git, GitHub.
А так хорошо 👍

2023-03-09 07:18 UTC, arybin93 commented on Git/Git_introduction.md
> +[Шпаргалка по Git](https://training.github.com/downloads/ru/github-git-cheat-sheet/) от GitHub на русском языке.
Может дать ещё ссылку на наш материал?
https://github.com/nnstu-appmath/kb/blob/5_git_introduction/Git/Git%20-%20commands.md

2023-03-09 07:18 UTC, arybin93 commented on Git/Git_introduction.md
> +Клонирование репозитория осуществляется командой `git clone`. Есть несколько способ клонировать репозиторий, но мы воспользуемся SSH-ключом. Посмотрите [видео](https://www.youtube.com/watch?v=4evR80g
По SSH может дать ссылку и на наш материал? 
https://github.com/nnstu-appmath/kb/blob/5_git_introduction/SSH/connecting_to_github_with_SSH.md

2023-03-09 07:18 UTC, arybin93 commented on Git/Git_introduction.md
> +У нас есть 2 варианта: превратить локальный каталог в репозиторий Git или клонировать существующий репозиторий Git.
Возможно, есть смысл рассмотреть эти два варианта отдельно? 
Мы на практике рассматривали вариант через клонирование репозитория с GitHub. При этом мы ещё добавляли тестовое issue и называли бранчи с использованием нашего наименования описанное здесь: https://github.com/nnstu-appmath#branch-naming

Если через git init, то по идее примерно всё так же. При этом шаг с SSH ключем всё равно нужен. Просто он появляется уже позднее, когда нам надо сделать push на GitHub (удаленный сервер).

Можно рассмотреть практику, сначала только git, без упоминания GitHub-а. 
Чтобы работать с кодом локально.

Но потом перейти к проблеме командной разработки, удаленного хранения репозитория или когда вы хотите получить какой-то проект локально, тогда нужен уже и SSH ключ, и GitHub, git clone, git remote.

То есть практика из двух частей, одна по git (установка, настройка, необходимая теория, git add, git commit, git log, git status, git branch, git merge).
Другая уже с GitHub (SSH, git remote, git push, git pull, Pull Requests)

2023-03-09 07:18 UTC, arybin93 commented on Git/Git_introduction.md
> +Итак, у нас имеется настоящий Git-репозиторий и рабочая копия файлов для некоторого проекта. Нам нужно сделать некоторые изменения и фиксировать «снимки» состояния (англ. __snapshots__ — снимки, фото
Как вариант, посмотреть то что у нас уже есть здесь https://github.com/nnstu-appmath/kb/blob/5_git_introduction/Git/git-architecture.md и взять что-нибудь отсюда, если нужно

2023-03-09 07:18 UTC, arybin93 commented on Git/Git_introduction.md
> +Каждый раз, когда вы делаете коммит, вы сохраняете снимок состояния вашего проекта, который позже вы можете восстановить или с которым можно сравнить текущее состояние.
Согласен c Матевеем, использование веток хорошо бы добавить, на нашей практике мы как раз это разбирали тоже (git branch, git checkout -b).
Про откат изменений, это не основы, но я тоже показывал на одной из практик, как вариант, можно добавить это в конце в виде ссылок, для дальнейшего обучения самостоятельно)

2023-10-05 08:10 UTC, arybin93 requested changes
Спасибо, Кирилл. Выглядит круто)
Добавил несколько улучшений, комментариев.
Можно пригласить ещё кого-нибудь из одногруппников посмотреть

2023-10-05 08:10 UTC, arybin93 commented on Git/README.md
> +```shell
или `git add .`

2023-10-05 08:10 UTC, arybin93 commented on Git/README.md
> +Но на самом деле git пытается быть лёгким и быстрым, так что он не просто слепо копирует весь проект каждый раз, а ужимает коммит в набор изменений или «дельту» между текущей версией и предыдущей. Эт
Можно добавить картинку отсюда или может прикрепить просто ссылку?

https://github.com/nnstu-appmath/kb/blob/5_git_introduction/Git/git-architecture.md#%D1%85%D1%80%D0%B0%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85-%D0%B2-git

2023-10-05 08:10 UTC, arybin93 commented on Git/README.md
> +* Индекс в Git — это специальная промежуточная область, в которой хранятся изменения файлов на пути от рабочей директории до репозитория. При выполнении коммита в него попадают только те изменения, к
Может здесь тоже картинку из презентации?
https://github.com/nnstu-appmath/kb/blob/5_git_introduction/Git/git-architecture.md#%D0%B2-git-%D0%B5%D1%81%D1%82%D1%8C-%D1%82%D1%80%D0%B8-%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D1%8B%D0%B5-%D1%81%D0%B5%D0%BA%D1%86%D0%B8%D0%B8-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0-%D1%80%D0%B0%D0%B1%D0%BE%D1%87%D0%B0%D1%8F-%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F-working-tree-%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D1%8C-%D0%B8%D0%BD%D0%B4%D0%B5%D0%BA%D1%81%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-staging-area-%D0%B8-%D0%BA%D0%B0%D1%82%D0%B0%D0%BB%D0%BE%D0%B3-git-git-directory

2023-10-05 08:10 UTC, arybin93 commented on Git/README.md
> +$ git commit
Если просто выполнить команду git commit, то откроется текстовый редактор, может для простоты начать с варианта?
```git commit -m "First commit"```

2023-10-05 08:10 UTC, arybin93 commented on Git/README.md
> +* Открывайте GitBash или терминал, вводите:
Может добавить ещё ссылку на материал? 

https://github.com/nnstu-appmath/kb/blob/5_git_introduction/SSH/connecting_to_github_with_SSH.md

2023-10-05 08:10 UTC, arybin93 commented on Git/README.md
> +* Заходим на [Github](https://github.com) регестрируемся.
регистрируемся или осуществляем логин если аккаунт уже есть?

2023-10-05 08:10 UTC, arybin93 commented on Git/README.md
> +![New key](./img/изображение_2023-10-02_165521842.png)
Картинку наверное поближе к команде `ssh-keygen -t ed25519 -b 4096` Или подписать, что пример запуска команды: `ssh-keygen -t ed25519 -b 4096`

2023-10-05 08:10 UTC, arybin93 commented on Git/README.md
> +* Копируем три команды и вставляем их в Git Bash.
Хорошо бы добавить объяснение про команду remote, кратко

2023-10-05 08:10 UTC, arybin93 commented on Git/README.md
> +**Создание новой ветки**
Может вставить немного инфы про ветки? Зачем нужны и что это такое, может взять что-то отсюда:
https://github.com/nnstu-appmath/kb/blob/5_git_introduction/Git/Git_introduction.md#%D0%B7%D0%B0%D1%87%D0%B5%D0%BC-%D0%BD%D1%83%D0%B6%D0%B5%D0%BD-git

2023-10-05 08:10 UTC, arybin93 commented on Git/README.md
> +* Merge, confirm merge, delete branch.
Предлагаю ещё добавить блок, по тому, как получить смёрженные изменения локально, то есть нужно перейти на master/main и выполнить git pull (стянуть) изменения. 
Ещё есть git fetch, она стягивает изменения, но не осуществляет merge с текущей веткой, тоже примеры бы привести.

И указать, про отдельные полезные темы, такие как merge conflicts и откат изменений (reset, revert), git stash, но это рассмотрим в рамках курса по необходимости.

2023-11-20 13:42 UTC, esinkirill commented on Git/README.md
> +$ git commit -m "First commit"
Убрал просто git commit

2023-11-20 13:46 UTC, esinkirill commented
@arybin93 review

2023-11-20 13:51 UTC, esinkirill commented
@yasha-nev review

2023-11-20 16:26 UTC, yasha-nev commented on Git/README.md
> +Как мы видим на данный момент у нас нет коммитов на ветке матер и сам git предлогает создать файл и добавить его. Давайте сделаем это:
мастер?

2023-11-20 16:26 UTC, yasha-nev commented on Git/README.md
> +Напишем ростенькую программу, далее нажимам ctrl+O и для выхода ctrl+X:
простенькую

2023-11-20 16:26 UTC, yasha-nev commented on Git/README.md
> +```
Куда добавим? Что add делает? Дальше сказано про поле Индекс, но в этот момент не ясно. Причем даже там не сказано что сделал add

2023-11-20 16:26 UTC, yasha-nev commented on Git/README.md
> +* Индекс в Git — это специальная промежуточная область, в которой хранятся изменения файлов на пути от рабочей директории до репозитория. При выполнении коммита в него попадают только те изменения, к
Второй раз про индекс

2023-11-20 16:26 UTC, yasha-nev commented on Git/README.md
> +* Заходи в папку где сохранились ключи, тот что .pub открываем с помощью блакнота и копируем содрежимое.
блокнот? содержимое?

2023-11-20 16:26 UTC, yasha-nev commented on Git/README.md
> +* Даллее будет такое окно:
Далее?

2023-11-20 16:26 UTC, yasha-nev commented on Git/README.md
> +* Кокгда вы все обсудили соглосовали, то можно делать merge - используется в Git, чтобы собрать воедино разветвленную историю. Команда git merge выполняет слияние отдельных направлений разработки, со
Когда? согласовали?

2023-11-20 16:26 UTC, yasha-nev commented on Git/README.md
> +
Можно тогда еще поднять тему ребейса. Пока ты пилил свою стороннюю ветку, основная ветка могла получить некоторые изменения, например от других разработчиков. git rebase обновляет твою стороннюю ветку с учетом новой версии основной(конечно там могут быть конфликты, которые необходимо решить)

2023-11-20 16:29 UTC, yasha-nev commented on Git/README.md
> +* [Git Bash](https://git-scm.com/downloads)-это приложение, которое обеспечивает работу командной строки Git в операционной системе. Это оболочка командной строки для включения git с помощью командно
`это приложение, которое обеспечивает работу командной строки Git в операционной системе`. git - это командная строка?

2023-11-20 16:37 UTC, yasha-nev commented on Git/README.md
> +Но на самом деле git пытается быть лёгким и быстрым, так что он не просто слепо копирует весь проект каждый раз, а ужимает коммит в набор изменений или «дельту» между текущей версией и предыдущей. Эт
Коммит это огромная копия проекта, но потом это не копия проекта, а набор изменений? Ужимает коммит? Сложно

2023-11-20 17:18 UTC, yasha-nev commented
Теперь вроде норм

2023-11-21 11:00 UTC, arybin93 approved these changes
Посмотрел, проделана большая работа спасибо!
Недочёты есть, но их уже будем исправлять постепенно.
Будем использовать как практику для второго курса в следующем семестре)

2023-11-21 11:06 UTC, merged