add git-commands file
nnstu-appmath/kb pull request #6
Opened 2022-09-12 09:13 UTC by morganika

2022-09-12 17:48 UTC, arybin93 requested changes
Спасибо, в целом хорошо, оставил некоторые минорные комментарии.
Как по мне, не хватает конечно, примеров хотя бы рядом с основными командами.
Но возможно, стоит, что-то вроде книги рецептов отдельно собирать

2022-09-12 17:48 UTC, arybin93 commented on Git/Git - commands.md
> +<h1>Git, основные команды</h1>
Можно использовать синтаксис [markdown](https://www.markdownguide.org/basic-syntax/#headings)

2022-09-12 17:48 UTC, arybin93 commented on Git/Git - commands.md
> +git pull – выгрузить изменения с удалённого репозитория<br>
Для переноса строк [line-breaks](https://www.markdownguide.org/basic-syntax/#line-breaks)

2022-09-12 17:48 UTC, arybin93 commented on Git/Git - commands.md
> +git unit – создать пустой репозиторий (предварительно переходим в нужное место через консоль) <br>
`git init` скорее всего опечатка

2022-09-12 17:48 UTC, arybin93 commented on Git/Git - commands.md
> + 
Предлагаю добавить ещё `git stash`, что думаете?

2022-09-12 17:48 UTC, arybin93 commented on Git/Git - commands.md
> +Инструкция по установке Git: https://git-scm.com/book/ru/v2/Введение-Установка-Git
Думаю, можно добавить также ссылку на первоначальную настройку? 
[Первоначальная настройка](https://git-scm.com/book/ru/v2/%D0%92%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5-%D0%9F%D0%B5%D1%80%D0%B2%D0%BE%D0%BD%D0%B0%D1%87%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-Git)

2022-09-17 11:20 UTC, IshuDivan approved these changes
Выглядит отлично, коротко и по делу. Возможно стоило уточнить больше терминологии для пользователей, которые впервые гит видят, но с другой стороны гугл им в помощь

2022-09-17 11:20 UTC, IshuDivan commented on Git/Git - commands.md
> +<h1>Git, основные команды</h1>
Возможно стоит отметить команды, которые потребуют первоначальной настройки, как выбор ника и почты (push origin) и т.п.

2022-09-21 12:18 UTC, PeshinaA approved these changes
Считаю, что все хорошо и проделана отличная работа.

2022-09-26 10:17 UTC, arybin93 approved these changes
Всё хорошо, спасибо за работу и учёт комментариев.
Если что-то потребуется потом ещё в будущем учтём.

2022-10-03 16:23 UTC, merged