add linux documentation
nnstu-appmath/kb pull request #8
Opened 2022-09-15 16:40 UTC by RuslanShamshetdinov

2022-09-18 13:53 UTC, arybin93 requested changes
Спасибо, в целом хорошо, добавил комментарии, как можно ещё улучшить. 
В идеале, подготовить какой-нибудь tutorial по которому можно быстро настроить linux локально или дать ссылку (например, через docker контейнер), подключиться к нему. И там например, пройтись по основным командам которые в материале представлены с объяснениями, что делаем и зачем.
Например, создали директорию, перешли в неё, добавили файл, отредактировали файл, поменяли permissions, попробовали поискать в файле (grep), попробовали поискать в каталоге. Посмотрели запущенные процессы и т.д. 
Т.е. не сразу всю информацию, а чтобы постепенно пройтись отталкиваясь от мелких задач и постепенно покрыть большую основных часть кейсов использования.

2022-09-18 13:53 UTC, arybin93 commented on Linux/Linux_documentation.md
> +9. **cat**
Думаю, полезно упомянуть про команду tail, head c примером использования

2022-09-18 13:53 UTC, arybin93 commented on Linux/Linux_documentation.md
> +
Хорошо бы добавить, какие редакторы доступны из консоли, nano (хотя бы), vi, vim для работы с файлами

2022-09-18 13:53 UTC, arybin93 commented on Linux/Linux_documentation.md
> +Данная статья не является полным курсом по знакомству с командами терминала Linux, так как количество команд является достаточно объемным. Более подробно можно познакомиться с командами и их уникальн
Можно добавить ссылки на используемый материал, полезные видео и статьи.
Например, ссылка на основной синтаксис bash-а: https://learnxinyminutes.com/docs/bash/

2022-09-18 13:53 UTC, arybin93 commented on Linux/Linux_documentation.md
> +#### **Базовые команды для работы с терминалом:** ####
Думаю, было бы ещё хорошо добавить материал, по тому как начать использовать Linux (Установка полноценной системы, использование Virtual Machine, использование docker контейнера, может ссылку на какую-нибудь онлайн консоль). Как считаешь?

2022-09-18 13:53 UTC, arybin93 commented on Linux/Linux_documentation.md
> +13. **alias**
Про alias это наверное больше для продвинутого использования, можно оставить, но вынести куда-нибудь в конец

2022-09-18 13:53 UTC, arybin93 commented on Linux/Linux_documentation.md
> +6. **chwon**
Думаю опечатка, имеется ввиду `chown`

2022-09-18 13:53 UTC, arybin93 commented on Linux/Linux_documentation.md
> +5. **chmod**
Хорошо бы добавить описание про виды permissions read/write/execute (777), пример как выдать права на выполнение программы или только на чтение

2022-09-18 13:53 UTC, arybin93 commented on Linux/Linux_documentation.md
> +```
Сюда можно добавить про Linux Pipe, хотя бы кратко и какой-нибудь пример использования, может что-то отсюда:
https://habr.com/ru/post/195152/

2022-09-18 13:53 UTC, arybin93 commented on Linux/Linux_documentation.md
> +4. inux Mint
Хорошо бы ещё описать хотя бы основные каталоги в системе linux, https://firstvds.ru/technology/linux-directories-structure. etc, var и другие.

2022-09-18 13:53 UTC, arybin93 commented on Linux/Linux_documentation.md
> +```
Тоже больше для администрирования и продвинутого использования можно добавить информацию про то, как посмотреть запущенные процессы в Linux (Ps -ef | top, htop), как убить процесс kill. И тут же объяснение про pid, процессы, сигналы, например, что-то отсюда можно взять: https://www.digitalocean.com/community/tutorials/how-to-use-ps-kill-and-nice-to-manage-processes-in-linux

2022-09-21 08:40 UTC, RuslanShamshetdinov commented on Linux/Linux_documentation.md
> +9. **cat**
Я учту все замечания, которые вы написали и добавлю их в свою небольшой справочник. В целом я понял все ваши комментарии, про Linux Pipe, если честно, не слышал, но будет самому интересно узнать. В команде «chown» действительно сделана опечатка. Согласен, что alias скорее для опытных пользователей, но ее функционал достаточно полезен, уберу ее в конец. Насчёт установки и настройки Linux: если я приведу ссылку на статью или даже ссылку на видео урок по настройке, будет нормально? Естественно, с добавлением своих комментариев и замечаний.

2022-09-21 11:43 UTC, PeshinaA commented on Linux/Linux_documentation.md
> +Существуют множество видов дистрибутивов Linux. Самые распространённые в мире дистрибутивами являются:
Я бы добавила ссылок: http://releases.ubuntu.com, https://www.debian.org, https://astralinux.ru. Еще, как по мне, в спике не хватает Red Hat Linux, CentOS(https://www.centos.org), openSUSE(https://www.opensuse.org) и Fedora(https://getfedora.org) (основанные на RPM дистрибутивы). У Linux Mint(https://linuxmint.com) скорее всего опечатка.

2022-09-21 11:54 UTC, PeshinaA commented on Linux/Linux_documentation.md
> +
Не хватает команд для выключения и перезагрузки, если у пользователя например Ubuntu Server и графической оболочки нет. Команды shutdown, reboot, halt, poweroff и ключи к ним.

2022-09-21 12:00 UTC, PeshinaA commented on Linux/Linux_documentation.md
> +
Также, думаю, было бы полезно добавить чуток команд для работы с сетью

2022-09-21 13:47 UTC, PeshinaA commented
Хорошо было бы добавить информацию про чистку логов и  базовые пути к папкам.

2022-09-25 11:46 UTC, MaxBushuev reviewed
В общем неплохо. Достаточно подробно разобраны команды и предыдущие замечания исправлены. Есть разве что небольшой вопрос по тексту. Являются ли файлы изображения бинарными? В тексте они помещены в отдельную категорию.

2022-09-25 12:14 UTC, PeshinaA approved these changes

2022-09-25 17:06 UTC, IrinaDogadina approved these changes
Это лучшая лекция по Линуксу из всех, что я видела!!!!

2022-09-25 17:11 UTC, dashakotova0702 approved these changes
Как пользователь Виндоус этот материал очень полезен и информативен! Руслан - молодец!
![image](https://user-images.githubusercontent.com/62749472/192156197-9a4212e9-26c2-412a-9b86-ef2955219fb2.png)

2022-09-26 09:59 UTC, arybin93 commented on Linux/Linux_documentation.md
> +9. **cat**
`Насчёт установки и настройки Linux: если я приведу ссылку на статью или даже ссылку на видео урок по настройке, будет нормально?` - Да, всё так.

2022-09-26 10:01 UTC, arybin93 approved these changes
Да, получилось хорошо, думаю можно мёржить и закрывать issue. Какие-то доработки будем уже потом делать, если потребуется)
На встрече, сегодня этот процесс проведём для демонстрации.

2022-09-26 10:25 UTC, Schepetova approved these changes

2022-09-26 16:15 UTC, merged